iastate_theme.settings:
  type: theme_settings
  label: "Iowa State Theme Settings"
  mapping:
    isu_navbar:
      type: integer
      label: "Show ISU navbar"
    features:
      type: mapping
      label: "Optional features"
      mapping:
        favicon:
          type: boolean
          label: "Use the favicon supplied by the theme"
    default_copyright:
      type: boolean
      label: "Use the defaults supplied by the theme"
    copyright_subject:
      type: mapping
      label: "Subject of copyright"
      mapping:
        type:
          type: string
          label: "Render type"
        text:
          type: string
          label: "Text value in for copyright"
        format:
          type: string
          label: "Format type"
    default_site_logo_alttext_url:
      type: boolean
      label: "Use the defaults supplied by the theme"
    site_logo_alttext:
      type: string
      label: "Text describing image"
    site_logo_url:
      type: uri
      label: "URL attribute"
    default_footer_logo:
      type: boolean
      label: "Use the defaults supplied by the theme"
    iastate_footer_logo_path:
      type: uri
      label: "Path to custom footer logo"
    iastate_footer_logo_alttext:
      type: string
      label: "Text describing image"
    iastate_footer_logo_url:
      type: uri
      label: "Custom footer logo url"
    default_support_extension:
      type: uri
      label: "Default Support Extension Link"
    support_extension:
      type: uri
      label: "Support Extension Link"
    default_social_footer:
      type: boolean
      label: "Show social media footer links block"
